version: "3"
services:
  server:
    image: dockerfile
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3307/dogukan?useSSL=false&useJDBCComplaintTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    networks:
      - enoca7
    restart: always
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    ports:
      - 3307:3306
    networks:
      - enoca7

    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=dogukan
      - MYSQL_PASSWORD=12345

networks:
  enoca7: